### PR TITLE
Changed IV generation to be actually random

### PR DESCRIPTION
**Pull request by agazso**
I propose to change the IV generation to use actual random with the `crypto` API, because if people find this blog and just copy the code as is, it will work but it will be broken because it always uses the same IV!

And it's not so difficult to generate an actual random.

### CODE REVIEW

**Comment by j-f1** [comment]
I think we cover this with

> We encrypt the content with that random key. In this case, we only encrypt the content once with the random key so we don't need an `iv` and can leave it filled with 0 ([I hope...](https://www.youtube.com/watch?v=LP1t_pzxKyE)).

but I see your point.

**Comment by agazso** [comment]
Oh, I missed that part entirely. If you use the same nonce all the time then it's likely that your encryption is very easy to break. See

https://en.wikipedia.org/wiki/Initialization_vector
and
https://en.wikipedia.org/wiki/Galois/Counter_Mode

The best practice is to store the IV along with the encrypted payload, for example prepend it as the first 12 bytes.

**Comment by j-f1** [comment]
Is that an issue if we’re only using each encryption key once, though?

**Comment by vjeux** [comment]
My understanding is that we are generating a new key each time and only using that key to encrypt the data once, so we don't need the IV and can use a constant for it. The challenge is that if we want to use the iv, then we'll need to also store it in the url and make it 12 bytes longer which is not ideal given that it doesn't add any additional protection.

You are right that this is error prone and why I added comments in the code about it. I'm not 100% sure how to prevent misuse there.

Note that for the collaborative editing, we are reusing the same key multiple times and are sending the iv. Because we have a channel to pass message in the clear to the machines decrypting it other than the URL, it is not a big issue there.

**Comment by agazso** [comment]
If you are sure you are generating a new key every time you change the document it may be ok to not use the IV.

Then maybe I don't understand the use case then, because this means that:
- for every version of the document you have a different link (with a different key)
- and that a link to an old version of the document won't be able to open the current version because the link contains an old key

Otherwise you are reusing the key _and_ the nonce and that leaves your encryption broken.

@vjeux it's not necessary to store the IV in the link because it does not have to be secret (just different every time you encrypt data with the same key). As I wrote before you can store it with your encrypted payload, for example by prepending it.

**Comment by dwelle** [comment]
> for every version of the document you have a different link (with a different key)

Yes

> and that a link to an old version of the document won't be able to open the current version because the link contains an old key

Yes. In fact, the old link simply links to a snapshot of the scene at the time of creation of that link. Since we don't have authentication, it would currently not make sense to have documents be updatable as anyone with the link could do it.

**Comment by vjeux** [comment]
Interesting, haven’t thought about putting the iv in the payload we upload to the server. That would work, but still be more complexity than necessary

**Pull request closed without merging**
