### PR TITLE
post: Enabling translations

### PR DESCRIPTION
**Pull request by lipis**
Fully open on how to form the copy.. if anyone is good with words feel free to edit :)

### [Preview](https://excalidraw-blog-git-crowdin.excalidraw-team.now.sh/enabling-translations/)

### CODE REVIEW

**Comment by vjeux** [comment]
This is a good start. I would spend more time explaining how the translation system works, why crowdin is super helpful...

You can talk about:
- the file structure
- the automatic updating PR
- the suggestions when translating
- the dashboard of language completion...

**Comment by vjeux** [comment]
I would also change the title to something more positive. "Coping" has a pretty negative connotation.

**Comment by j-f1** [comment]
“Enabling translations?”

**Comment by j-f1** [comment]
Looks good so far! I think it could use some discussion of how translation works in practice — adding new strings to translate, and how our `i18n` and language dropdown work.

**Comment by mtliendo** [comment]
Did a pass on the copy and made some tweaks. Notable changes:
* Slight spelling changes
* Removed the nested list of features in favor of a paragraph and single-level feature list
* Update consistency of the tense being used
* Removed the word "you" in the blog in favor of addressing the audience as a whole
    - Note, I kept the word "you" in the bottom section since this is technically a call-to-action
* Connotations were updated to be inline with the intended feeling

As @vjeux mentioned, you can go deeper into everything that crowdin can do (I've never heard of it), but I think the distinction is if this post is an announcement of translations being added, or a plug on what Crowdin can do.  A nice middle ground, would be to add a gif or two showing crowdin in action.

**Pull request closed without merging**
